[Bump] New bump command
n26/bob pull request #10
Opened 2018-04-12 13:30 UTC by ohitsdaniel

Adds a bump command that can be used to increase the build number in iOS projects in all specified .plist files by one.

2018-04-12 15:24 UTC, bernhard-eiling approved these changes

2018-04-13 12:59 UTC, i-dama requested changes

2018-04-13 12:59 UTC, i-dama commented on Sources/Bob/Commands/Bump/BumpCommand.swift
> +    public init(gitHub: GitHub, defaultBranch: BranchName, plistPaths: [String], author: Author, message: String = "[General] Bumps version to <version> (<buildNumber>).") {
Can we use the same default message as `align` since it's doing the same thing?

2018-04-13 12:59 UTC, i-dama commented on Sources/Bob/Commands/Bump/BumpCommand.swift
> +                let versionString = PListHelpers.extractStringValue(from: version)
If the `version` isn't found, the result will be `""`, and the command will change the version to an empty string. I believe we should `throw` here.

2018-04-13 13:13 UTC, ohitsdaniel commented on Sources/Bob/Commands/Bump/BumpCommand.swift
> +    public init(gitHub: GitHub, defaultBranch: BranchName, plistPaths: [String], author: Author, message: String = "[General] Bumps version to <version> (<buildNumber>).") {
Fine.

2018-04-13 13:52 UTC, i-dama approved these changes
LGTM 👍

2018-04-13 13:52 UTC, merged